#pragma once


#define CONTROL_SELECT					0
#define CONTROL_SELECT_DEFAULT			90

#define CONTROL_CANCEL					1
#define CONTROL_CANCEL_DEFAULT			88


#define CONTROL_MOVE_LEFT				2
#define CONTROL_MOVE_LEFT_DEFAULT		263

#define CONTROL_MOVE_RIGHT				3
#define CONTROL_MOVE_RIGHT_DEFAULT		262

#define CONTROL_MOVE_UP					4
#define CONTROL_MOVE_UP_DEFAULT			265

#define CONTROL_MOVE_DOWN				5
#define CONTROL_MOVE_DOWN_DEFAULT		264


#define CONTROL_ROTATE_LEFT				6
#define CONTROL_ROTATE_LEFT_DEFAULT		65

#define CONTROL_ROTATE_RIGHT			7
#define CONTROL_ROTATE_RIGHT_DEFAULT	83
